### ISSUE TITLE
增强模式未生效

### ISSUE THREAD

**Issue by Windlee-Lin** [MiPushFramework/MiPushEnhancement#1]
使用v5.0.6 sandhook edxposed，已安装原版mopush，edxposed内模块已勾选，但提示增强模式未生效

**Comment by MlgmXyysd** [comment]
请提供更多信息
```
Android version:
ROM & version:
Magisk version:
Magisk Manager version:
EdXposed version:
EdXposed Manager version:
MiPush version:
MiPush Manager version:
MiPush Enhancement version:
Magisk modules list:
Xposed modules list:
EdXposed verbose log:
```

**Comment by Windlee-Lin** [comment]
Android version: 10
ROM & version: Resurrection Remix 8.5.8 
Magisk version: 20.4
Magisk Manager version: 7.5.1
EdXposed version: v0.4.6.2(YAHFA)
EdXposed Manager version: 4.5.7
MiPush version: 0.3.7 20200505
MiPush Manager version: 0.3.7 20200505
MiPush Enhancement version: 1.2
Magisk modules list: RIRU;RIRU mipushfake…
Xposed modules list: thanox; xposed  edge; push
EdXposed verbose log:

**Comment by H-xiaoH** [comment]
遇到相同的问题。

Android version:Android Q
ROM & version:AOSP 10
Magisk version:20.4(20400)
Magisk Manager version:7.5.1(267)
EdXposed version:0.4.6.2(4529)(SandHook)
EdXposed Manager version:4.5.7(45700)
MiPush version:0.3.7.20200505.b69e434_framework
MiPush Manager version:0.3.7.20200505.b69e434
MiPush Enhancement version:1.2
Magisk modules list:Riru;Riru-EdXposed…
Xposed modules list:EdXposed Manager;Push;MiPush Framework Enhancement…
EdXposed verbose log:

**Comment by MlgmXyysd** [comment]
> 遇到相同的问题。
> 
> Android version:Android Q
> ROM & version:AOSP 10
> Magisk version:20.4(20400)
> Magisk Manager version:7.5.1(267)
> EdXposed version:0.4.6.2(4529)(SandHook)
> EdXposed Manager version:4.5.7(45700)
> MiPush version:0.3.7.20200505.b69e434_framework
> MiPush Manager version:0.3.7.20200505.b69e434
> MiPush Enhancement version:1.2
> Magisk modules list:Riru;Riru-EdXposed…
> Xposed modules list:EdXposed Manager;Push;MiPush Framework Enhancement…
> EdXposed verbose log:

请完整提供以下内容
> Magisk modules list:Riru;Riru-EdXposed…
> Xposed modules list:EdXposed Manager;Push;MiPush Framework Enhancement…
> EdXposed verbose log:

**Comment by H-xiaoH** [comment]
Magisk modules:
- Advanced Charging Controller;
- Riru-Core;
- Riru-EdXposed;
- Riru-Enhanced mode for Storage Isolation;
- Riru-Location Report Enabler;
- Riru-MiPushFake;
- Systemless Hosts;
- Universal GMS Doze;
- Wifi Bonding

Xposed modules 
- Card Emulator Pro;
- EdXposed Manager;
- Fingerprint pay;
- Greenify;
- MDWechat(官改);
- MiPush Framework Enhancement;
- Push;
- QNotified;
- XposedSmsCode;
- 云村清洁工;
- 运动加速器

EdXposed verbose log:
<details>
<summary>Edit: 日志过长已隐藏</summary>

```--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
Telegram channel: @EdXposed
--------- beginning of information
Manufacturer: Google
Brand: google
Device: blueline
Product: blueline
Model: Pixel 3
Fingerprint: google/blueline/blueline:10/QQ3A.200805.001/6578210:user/release-keys
ROM description: blueline-user 10 QQ3A.200805.001 6578210 release-keys
Architecture: arm64-v8a
Android build: QQ3A.200805.001
Android version: 10
Android sdk: 29
EdXposed version: v0.4.6.2 (4529) (SandHook)
EdXposed api: 91.0
Riru version: v21.3 (36)
Riru api: 7
Magisk: 20.4 (20400)
--------- beginning of main
--------- beginning of system
08-28 17:30:53.855   960   960 I EdXposed: onModuleLoaded: welcome to EdXposed!
08-28 17:30:53.855   960   960 I EdXposed: Start to install inline hooks
08-28 17:30:53.855   960   960 I EdXposed: Using api level 29
08-28 17:30:53.855   960   960 I EdXposed: Start to install Riru hook
08-28 17:30:53.869   960   960 I EdXposed: Riru hooks installed
08-28 17:30:53.983   960   960 I EdXposed: ART hooks installed
08-28 17:30:53.983   960   960 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
08-28 17:30:53.983   960   960 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
08-28 17:30:54.322   961   961 I EdXposed: onModuleLoaded: welcome to EdXposed!
08-28 17:30:54.322   961   961 I EdXposed: Start to install inline hooks
08-28 17:30:54.322   961   961 I EdXposed: Using api level 29
08-28 17:30:54.322   961   961 I EdXposed: Start to install Riru hook
08-28 17:30:54.335   961   961 I EdXposed: Riru hooks installed
08-28 17:30:54.408   961   961 I EdXposed: ART hooks installed
08-28 17:30:54.409   961   961 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
08-28 17:30:54.409   961   961 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
08-28 17:30:54.430   960   960 I EdXposed: using installer org.meowcat.edxposed.manager
08-28 17:30:54.430   960   960 I EdXposed: data path prefix: /data/user_de/0/
08-28 17:30:54.430   960   960 I EdXposed:   application list mode: true
08-28 17:30:54.430   960   960 I EdXposed:     using whitelist: false
08-28 17:30:54.430   960   960 I EdXposed:   dynamic modules mode: true
08-28 17:30:54.430   960   960 I EdXposed:   resources hook: true
08-28 17:30:54.430   960   960 I EdXposed:   deopt boot image: false
08-28 17:30:54.430   960   960 I EdXposed:   no module log: false
08-28 17:30:54.430   960   960 I EdXposed:   blacklist: com.google.android.gms
08-28 17:30:54.430   960   960 I EdXposed:   blacklist: com.google.android.gsf
08-28 17:30:54.584   961   961 I EdXposed: using installer org.meowcat.edxposed.manager
08-28 17:30:54.585   961   961 I EdXposed: data path prefix: /data/user_de/0/
08-28 17:30:54.585   961   961 I EdXposed:   application list mode: true
08-28 17:30:54.585   961   961 I EdXposed:     using whitelist: false
08-28 17:30:54.585   961   961 I EdXposed:   dynamic modules mode: true
08-28 17:30:54.585   961   961 I EdXposed:   resources hook: true
08-28 17:30:54.585   961   961 I EdXposed:   deopt boot image: false
08-28 17:30:54.585   961   961 I EdXposed:   no module log: false
08-28 17:30:54.585   961   961 I EdXposed:   blacklist: com.google.android.gms
08-28 17:30:54.585   961   961 I EdXposed:   blacklist: com.google.android.gsf
08-28 17:30:55.869   960   960 I EdXposed-Bridge: Loading modules from /data/app/com.surcumference.fingerprintpay-jKO5n8HKQ-XxLND8cKOakg==/base.apk
08-28 17:30:55.935   960   960 I EdXposed-Bridge:   Loading class com.yyxx.wechatfp.xposed.WalletBaseUI
08-28 17:30:55.937   960   960 I EdXposed-Bridge: Loading modules from /data/app/com.github.tianma8023.xposed.smscode-uB_ZqAI_Lukzg1GY6qRg9w==/base.apk
08-28 17:30:56.045   960   960 I EdXposed-Bridge:   Loading class com.tianma.xsmscode.xp.HookEntry
08-28 17:30:56.047   960   960 I EdXposed-Bridge: Loading modules from /data/app/com.qianbajin.sportaccelerator-Dbgf2bvhv9k1jn4HQgZyxA==/base.apk
08-28 17:30:56.062   960   960 I EdXposed-Bridge:   Loading class com.qianbajin.sportaccelerator.SportHook
08-28 17:30:56.067   960   960 I EdXposed-Bridge: Loading modules from /data/app/com.joshcai.mdwechat-lAS5WJAWQqSpuq04vxMi5g==/base.apk
08-28 17:30:56.214   960   960 I EdXposed-Bridge:   Loading class com.blanke.mdwechat.WechatHook
08-28 17:30:56.218   960   960 I EdXposed-Bridge: Loading modules from /data/app/org.meowcat.xposed.mipush-3-c3w6wjsRYLpIo34ofzkw==/base.apk
08-28 17:30:56.302   960   960 I EdXposed-Bridge:   Loading class org.meowcat.xposed.mipush.Enhancement
08-28 17:30:56.302   960   960 I EdXposed-Bridge: Loading modules from /data/app/me.zjns.lovecloudmusic-T1R1hN54SGjdwmIQUmd1jg==/base.apk
08-28 17:30:56.315   960   960 I EdXposed-Bridge:   Loading class me.zjns.lovecloudmusic.HookInit
08-28 17:30:56.317   960   960 I EdXposed-Bridge: Loading modules from /data/app/nil.nadph.qnotified-sKs5ReeqlP6_fBKMrSbqKA==/base.apk
08-28 17:30:56.345   960   960 I EdXposed-Bridge:   Loading class nil.nadph.qnotified.HookEntry
08-28 17:30:56.350   960   960 I EdXposed-Bridge: Loading modules from /data/app/org.meowcat.edxposed.manager-QkGMRe6BLUwhh0GCmYzKwg==/base.apk
08-28 17:30:56.651   960   960 I EdXposed-Bridge:   Loading class org.meowcat.edxposed.manager.xposed.Enhancement
08-28 17:30:56.652   960   960 I EdXposed-Bridge: Loading modules from /data/app/com.oasisfeng.greenify-ud8J0_QV1UCnDoN4Pvy73A==/base.apk
08-28 17:30:56.801   960   960 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
08-28 17:30:56.803   960   960 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.SettingsPatch
08-28 17:30:56.804   960   960 I EdXposed-Bridge: Loading modules from /data/app/com.yuanwofei.cardemulator.pro-TXQHZCCVSluWwBfTVz3fzA==/base.apk
08-28 17:30:56.883   960   960 I EdXposed-Bridge:   Loading class com.yuanwofei.cardemulator.xposed.MainHook
08-28 17:30:56.883   960   960 I EdXposed-Bridge: Loading modules from /data/app/com.xiaomi.xmsf-TZ-oCiy8K7TwO9V6S-WywA==/base.apk
08-28 17:30:57.062   960   960 I EdXposed-Bridge:   Loading class com.xiaomi.xposed.hook.MiPushEnhanceHook
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: MiPushEnhanceHook: get config: java.lang.NullPointerException: Attempt to read from field 'int android.content.pm.ApplicationInfo.uid' on a null object reference
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: 	at com.xiaomi.xposed.hook.MiPushEnhanceHook.handleLoadPackage(MiPushEnhanceHook.java:78)
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.impl.StartBootstrapServices.beforeHookedMethod(StartBootstrapServices.java:36)
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:357)
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: 	at SandHookerNew_76sqduusglom4enahqif5d7ntb.hook(Unknown Source:46)
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: 	at com.android.server.SystemServer.run(SystemServer.java:511)
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: 	at com.android.server.SystemServer.main(SystemServer.java:350)
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
08-28 17:30:57.446  1547  1547 I EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
08-28 17:31:01.714  2071  2071 I EdXposed-Bridge: Do NOT use TaiChi anyway\n请不要使用太极或无极
08-28 17:31:01.897  2258  2258 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.quicinc.cne.CNEService
08-28 17:31:01.897  2258  2258 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.quicinc.cne.CNEService
08-28 17:31:01.965  2258  2258 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
08-28 17:31:02.362  2341  2341 I EdXposed-Bridge: XSmsCode: SmsCode initializing
08-28 17:31:02.362  2341  2341 I EdXposed-Bridge: XSmsCode: Phone manufacturer: Google
08-28 17:31:02.362  2341  2341 I EdXposed-Bridge: XSmsCode: Phone model: Pixel 3
08-28 17:31:02.362  2341  2341 I EdXposed-Bridge: XSmsCode: Android version: 10
08-28 17:31:02.362  2341  2341 I EdXposed-Bridge: XSmsCode: Xposed bridge version: 91
08-28 17:31:02.362  2341  2341 I EdXposed-Bridge: XSmsCode: SmsCode version: 2.2.3 (43)
08-28 17:31:02.362  2341  2341 I EdXposed-Bridge: XSmsCode: Hooking InboundSmsHandler constructor for android v24+
08-28 17:31:02.372  2341  2341 I EdXposed-Bridge: XSmsCode: SmsCode initialize completely
08-28 17:31:03.590  2569  2569 I EdXposed-Bridge: Do NOT use TaiChi anyway\n请不要使用太极或无极
08-28 17:31:03.851  2640  2640 I EdXposed-Bridge: Do NOT use TaiChi anyway\n请不要使用太极或无极
08-28 17:31:06.013  3113  3113 I EdXposed-Bridge: Do NOT use TaiChi anyway\n请不要使用太极或无极
08-28 17:31:07.717  3283  3283 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.nfc
08-28 17:31:07.717  3283  3283 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.nfc
08-28 17:31:07.911  3283  3283 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
08-28 17:31:07.919  3341  3341 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.SSRestartDetector
08-28 17:31:07.919  3341  3341 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.SSRestartDetector
08-28 17:31:08.254  3341  3341 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
08-28 17:31:08.849  3356  3356 I EdXposed-Bridge: Do NOT use TaiChi anyway\n请不要使用太极或无极
08-28 17:31:09.581   961   961 I EdXposed-Bridge: Loading modules from /data/app/com.surcumference.fingerprintpay-jKO5n8HKQ-XxLND8cKOakg==/base.apk
08-28 17:31:09.901   961   961 I EdXposed-Bridge:   Loading class com.yyxx.wechatfp.xposed.WalletBaseUI
08-28 17:31:09.903   961   961 I EdXposed-Bridge: Loading modules from /data/app/com.github.tianma8023.xposed.smscode-uB_ZqAI_Lukzg1GY6qRg9w==/base.apk
08-28 17:31:10.033   961   961 I EdXposed-Bridge:   Loading class com.tianma.xsmscode.xp.HookEntry
08-28 17:31:10.035   961   961 I EdXposed-Bridge: Loading modules from /data/app/com.qianbajin.sportaccelerator-Dbgf2bvhv9k1jn4HQgZyxA==/base.apk
08-28 17:31:10.045   961   961 I EdXposed-Bridge:   Loading class com.qianbajin.sportaccelerator.SportHook
08-28 17:31:10.049   961   961 I EdXposed-Bridge: Loading modules from /data/app/com.joshcai.mdwechat-lAS5WJAWQqSpuq04vxMi5g==/base.apk
08-28 17:31:10.354   961   961 I EdXposed-Bridge:   Loading class com.blanke.mdwechat.WechatHook
08-28 17:31:10.356   961   961 I EdXposed-Bridge: Loading modules from /data/app/org.meowcat.xposed.mipush-3-c3w6wjsRYLpIo34ofzkw==/base.apk
08-28 17:31:10.442   961   961 I EdXposed-Bridge:   Loading class org.meowcat.xposed.mipush.Enhancement
08-28 17:31:10.443   961   961 I EdXposed-Bridge: Loading modules from /data/app/me.zjns.lovecloudmusic-T1R1hN54SGjdwmIQUmd1jg==/base.apk
08-28 17:31:10.447   961   961 I EdXposed-Bridge:   Loading class me.zjns.lovecloudmusic.HookInit
08-28 17:31:10.448   961   961 I EdXposed-Bridge: Loading modules from /data/app/nil.nadph.qnotified-sKs5ReeqlP6_fBKMrSbqKA==/base.apk
08-28 17:31:10.466   961   961 I EdXposed-Bridge:   Loading class nil.nadph.qnotified.HookEntry
08-28 17:31:10.466   961   961 I EdXposed-Bridge: Loading modules from /data/app/org.meowcat.edxposed.manager-QkGMRe6BLUwhh0GCmYzKwg==/base.apk
08-28 17:31:10.769   961   961 I EdXposed-Bridge:   Loading class org.meowcat.edxposed.manager.xposed.Enhancement
08-28 17:31:10.770   961   961 I EdXposed-Bridge: Loading modules from /data/app/com.oasisfeng.greenify-ud8J0_QV1UCnDoN4Pvy73A==/base.apk
08-28 17:31:10.901   961   961 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
08-28 17:31:10.905   961   961 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.SettingsPatch
08-28 17:31:10.905   961   961 I EdXposed-Bridge: Loading modules from /data/app/com.yuanwofei.cardemulator.pro-TXQHZCCVSluWwBfTVz3fzA==/base.apk
08-28 17:31:10.968   961   961 I EdXposed-Bridge:   Loading class com.yuanwofei.cardemulator.xposed.MainHook
08-28 17:31:10.969   961   961 I EdXposed-Bridge: Loading modules from /data/app/com.xiaomi.xmsf-TZ-oCiy8K7TwO9V6S-WywA==/base.apk
08-28 17:31:11.071   961   961 I EdXposed-Bridge:   Loading class com.xiaomi.xposed.hook.MiPushEnhanceHook
08-28 17:31:12.032  3946  3946 I EdXposed-Bridge: Do NOT use TaiChi anyway\n请不要使用太极或无极
08-28 17:31:14.045  4444  4444 I EdXposed-Bridge: WeChatFp [initWechat](WalletBaseUI.java:52) loaded: [com.tencent.mm] version:3.9.9
08-28 17:31:14.178  4444  4444 I EdXposed-Bridge: SportAccelerator-1.6.2:readable:false  exists:false  canRead:false  AbsolutePath/data/data/com.qianbajin.sportaccelerator/shared_prefs/com.qianbajin.sportaccelerator_preferences.xml
08-28 17:31:14.178  4444  4444 I EdXposed-Bridge: SportAccelerator-1.6.2:加载资源失败,没有权限?尝试启动一下本App,然后按返回键退出试试!
08-28 17:31:14.178  4444  4444 I EdXposed-Bridge: SportAccelerator-1.6.2:加载:com.tencent.mm  6.3.17  pid:4444  微信开关:true  每天首次增加:6998  每次增加:2998  步数上限:29998
08-28 17:31:14.180  4444  4444 I EdXposed-Bridge: SportAccelerator-1.6.2:微信步数文件不存在
08-28 17:31:14.180  4444  4444 I EdXposed-Bridge: SportAccelerator-1.6.2:加载:com.tencent.mm  pid:4444  传感器加速:true
08-28 17:31:14.182  4444  4444 I EdXposed-Bridge: SportAccelerator-1.6.2:读取微信步数异常
08-28 17:31:14.184  4444  4444 I EdXposed-Bridge: SportAccelerator-1.6.2:printLog:false  rate:4  gain:29998
08-28 17:31:14.323  4552  4552 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.android.bluetooth
08-28 17:31:14.323  4552  4552 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.android.bluetooth
08-28 17:31:14.411  4552  4552 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
08-28 17:31:15.734  4444  4444 I EdXposed-Bridge: WeChatFp [beforeHookedMethod](WalletBaseUI.java:56) Application onCreate
08-28 17:31:15.738  4444  4444 I EdXposed-Bridge: WeChatFp [main](XposedWeChatPlugin.java:76) Xposed plugin init version: 3.9.9
08-28 17:31:15.763  4444  4444 I EdXposed-Bridge: WeChatFp [main](XposedWeChatPlugin.java:81) WeChat Version code:1691
08-28 17:31:16.077  4978  4978 D EdXposedManager: ApplicationList: Force add modules to list
08-28 17:31:20.417  5390  5390 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.RilConfigService
08-28 17:31:20.417  5390  5390 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.RilConfigService
08-28 17:31:20.492  5390  5390 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
08-28 17:31:31.862  6275  6275 I EdXposed-Bridge: Do NOT use TaiChi anyway\n请不要使用太极或无极
08-28 17:31:32.083  6301  6301 I EdXposed-Bridge: Do NOT use TaiChi anyway\n请不要使用太极或无极
08-28 17:31:32.368  6329  6329 I EdXposed-Bridge: Do NOT use TaiChi anyway\n请不要使用太极或无极```
</details>

**Comment by MlgmXyysd** [comment]
在模块设置中重新选择一下工作模式后重启试一试

另，不要重复勾选Push和增强模块

**Comment by H-xiaoH** [comment]
增强模式状态已生效，非常感谢。
